# Generated by Django 6.0.1 on 2026-01-28 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencia',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='referencia',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.TextField()),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=7)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='garage/')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage', to='cv.perfil')),
            ],
        ),
    ]
