# Generated by Django 6.0.1 on 2026-01-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_remove_referencia_descripcion_alter_referencia_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
