# Generated by Django 6.0.1 on 2026-01-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_perfil_cedula_perfil_direccion_perfil_estado_civil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='direccion',
        ),
        migrations.AddField(
            model_name='perfil',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='licencia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefonos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='trabajo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='perfil',
            name='web',
            field=models.URLField(blank=True),
        ),
    ]
