# Generated by Django 6.0.1 on 2026-01-28 12:31

import cv.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_remove_perfil_direccion_perfil_domicilio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='educacion',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterField(
            model_name='certificado',
            name='fecha',
            field=models.DateField(help_text='Entre 2007 y 2026', validators=[cv.models.validate_certificate_year]),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Entre 2007 y 2026 (opcional)', null=True, validators=[cv.models.validate_certificate_year]),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_inicio',
            field=models.DateField(help_text='Entre 2007 y 2026', validators=[cv.models.validate_certificate_year]),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Entre 2007 y 2026 (opcional)', null=True, validators=[cv.models.validate_certificate_year]),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fecha_inicio',
            field=models.DateField(help_text='Entre 2007 y 2026', validators=[cv.models.validate_certificate_year]),
        ),
        migrations.AlterField(
            model_name='garage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nivel',
            field=models.IntegerField(help_text='Nivel del 1 al 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(help_text='Exactamente 10 dígitos numéricos', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cedula', message='La cédula debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Debe estar entre 1980 y el año actual', validators=[cv.models.validate_birth_year]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='licencia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
