# Generated by Django 6.0.1 on 2026-01-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_alter_certificado_options_alter_educacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(default='', upload_to='certificados/'),
            preserve_default=False,
        ),
    ]
