# Generated by Django 6.0.1 on 2026-01-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_certificado_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
