# Generated by Django 6.0.1 on 2026-01-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_cambiar_imagen_a_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='imagen',
        ),
    ]
