# Generated by Django 6.0.1 on 2026-01-28 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_remove_certificado_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='educacion',
            options={'ordering': ['-fecha_inicio'], 'verbose_name_plural': 'Educación'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['-fecha_inicio'], 'verbose_name_plural': 'Experiencias'},
        ),
        migrations.AlterModelOptions(
            name='garage',
            options={'verbose_name': 'Producto de Garage', 'verbose_name_plural': 'Productos de Garage'},
        ),
        migrations.AlterModelOptions(
            name='habilidad',
            options={'ordering': ['-nivel', 'nombre'], 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='referencia',
            options={'verbose_name_plural': 'Referencias'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='licencia',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='lugar_nacimiento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefonos',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='trabajo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='web',
        ),
        migrations.AlterField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(blank=True, help_text='Imagen o PDF del certificado - Se guarda en Azure: media/certificados/', null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Dejar vacío si está en curso', null=True),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Dejar vacío si es empleo actual', null=True),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='garage',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Visible en el sitio'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='estadoproducto',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40, verbose_name='Estado del producto'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto - Se guarda en Azure: media/garage/', null=True, upload_to='garage/'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='nombreproducto',
            field=models.CharField(max_length=100, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, help_text='Precio en dólares', max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nivel',
            field=models.IntegerField(help_text='Nivel de dominio: 1 (Básico) a 5 (Experto)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de perfil - Se guarda en Azure: media/perfil/', null=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='demo',
            field=models.URLField(blank=True, help_text='URL de demo o sitio en vivo', null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='github',
            field=models.URLField(blank=True, help_text='URL del repositorio', null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tecnologias',
            field=models.CharField(help_text='Tecnologías separadas por comas: Python, Django, Azure', max_length=300),
        ),
    ]
