# Generated by Django 6.0.1 on 2026-01-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_alter_certificado_options_alter_educacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='licencia',
            field=models.CharField(blank=True, help_text='Ej: Tipo B', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
