# Generated by Django 6.0.1 on 2026-01-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_perfil_cedula_perfil_estado_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='trabajo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Trabajo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfonos'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ubicacion',
            field=models.CharField(max_length=100, verbose_name='Ubicación General (Ciudad/País)'),
        ),
    ]
