# Generated by Django 6.0.1 on 2026-01-28 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_perfil_domicilio_perfil_trabajo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Reconocimiento')),
                ('otorgado_por', models.CharField(max_length=200, verbose_name='Entidad que otorga')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, help_text='Diploma o evidencia (Imagen/PDF)', null=True, upload_to='reconocimientos/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='cv.perfil')),
            ],
            options={
                'verbose_name_plural': 'Reconocimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
