# Generated by Django 6.0.1 on 2026-01-29 03:55

import cv.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_reconocimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='fecha',
            field=models.DateField(help_text='Fecha de emisión (2007 en adelante)', validators=[cv.models.validate_certificate_year]),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validate_certificate_year]),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_inicio',
            field=models.DateField(validators=[cv.models.validate_certificate_year]),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validate_certificate_year]),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fecha_inicio',
            field=models.DateField(validators=[cv.models.validate_certificate_year]),
        ),
        migrations.AlterField(
            model_name='garage',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='garage',
            name='estadoproducto',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40),
        ),
        migrations.AlterField(
            model_name='garage',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='garage/'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='nombreproducto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='garage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nivel',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(default='', help_text='Debe tener 10 dígitos exactos.', max_length=10, unique=True, validators=[cv.models.validate_cedula_ecuador], verbose_name='Cédula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01', help_text='Año permitido: 1980 en adelante.', validators=[cv.models.validate_birth_year], verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tecnologias',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='reconocimientos/'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='fecha',
            field=models.DateField(help_text='Fecha de obtención (2007 en adelante)', validators=[cv.models.validate_certificate_year]),
        ),
    ]
