# Generated by Django 6.0.1 on 2026-01-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_alter_certificado_archivo_alter_certificado_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen generada automáticamente desde el PDF', null=True, upload_to='certificados/img/'),
        ),
    ]
