# Generated by Django 6.0.1 on 2026-02-01 20:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0016_certificado_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidad',
            options={'ordering': ['orden', 'categoria', 'nombre'], 'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AddField(
            model_name='habilidad',
            name='categoria',
            field=models.CharField(default='General', help_text='Ej: Frontend, Backend, Database, DevOps', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habilidad',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de aparición'),
        ),
        migrations.AddField(
            model_name='habilidad',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='cv.perfil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nivel',
            field=models.IntegerField(help_text='Porcentaje de dominio (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nombre',
            field=models.CharField(help_text='Ej: Python, Django, React', max_length=100),
        ),
    ]
