# Generated by Django 6.0.1 on 2026-02-01 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0017_alter_habilidad_options_habilidad_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='educacion', to='cv.perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencia',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiencia', to='cv.perfil'),
            preserve_default=False,
        ),
    ]
